import { test, expect, type Page } from '@playwright/test'
import { wavSample } from '../fixtures/audio'
async function load(page: Page, playlist = false) {
  await page.goto('/')
  await page.getByLabel('Select library files', { exact: true }).setInputFiles([
    ...['A', 'B', 'C'].map(name => ({ name: `${name}.wav`, mimeType: 'audio/wav', buffer: Buffer.from(wavSample(30)) })),
    ...(playlist ? [{ name: 'List.m3u8', mimeType: 'audio/x-mpegurl', buffer: Buffer.from('#EXTM3U\nA.wav\nB.wav\nC.wav\n') }] : []),
  ])
  await expect(page.locator('.track-title strong')).toHaveText(['A', 'B', 'C'])
}
test('library playback works before and after empty creation without adding tracks', async ({ page }, info) => {
  test.skip(info.project.name === 'webkit' && process.platform === 'win32', 'Windows WebKit has no native audio decoder.')
  await load(page)
  await expect(page.getByRole('button', { name: 'Add A to playlist', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: 'Play B', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Pause', exact: true })).toBeVisible()
  await expect(page.locator('.now-playing strong')).toHaveText('B')
  await page.getByRole('button', { name: 'New playlist', exact: true }).click()
  await page.getByRole('button', { name: 'Create draft', exact: true }).click()
  await expect(page.locator('.now-playing strong')).toHaveText('B')
  await expect(page.locator('.track-title strong')).toHaveCount(0)
  await page.getByRole('tab', { name: 'All tracks', exact: true }).click()
  await page.getByRole('button', { name: 'Next track', exact: true }).click()
  await expect(page.locator('.now-playing strong')).toHaveText('C')
  await page.getByRole('button', { name: 'Actions for A', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Add & Play', exact: true }).click()
  await expect(page.locator('.now-playing strong')).toHaveText('A')
  await page.getByRole('tab', { name: 'Playlist', exact: true }).click()
  await expect(page.locator('.track-title strong')).toHaveText(['A'])
})
test('a filtered browse queue remains stable when search changes', async ({ page }, info) => {
  test.skip(info.project.name === 'webkit' && process.platform === 'win32', 'Windows WebKit has no native audio decoder.')
  await load(page)
  await page.getByRole('textbox', { name: 'Search tracks', exact: true }).fill('B')
  await page.getByRole('button', { name: 'Play B', exact: true }).click()
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await page.getByRole('button', { name: 'Next track', exact: true }).click()
  await expect(page.locator('.now-playing strong')).toHaveText('Ready when you are')
})
test('context menus preserve groups, support keyboard navigation, and restore focus', async ({ page }) => {
  await load(page, true)
  await page.getByRole('checkbox', { name: 'Select A', exact: true }).check()
  await page.getByRole('checkbox', { name: 'Select C', exact: true }).check()
  const row = page.locator('.track-row').filter({ has: page.getByRole('button', { name: 'Play A', exact: true }) })
  await row.click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Remove from playlist', exact: true }).click()
  await expect(page.locator('.track-title strong')).toHaveText(['B'])
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await row.focus(); await page.keyboard.press('Shift+F10')
  await expect(page.getByRole('menu', { name: 'Track actions' })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: 'Play', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('menuitem', { name: 'Remove from playlist', exact: true })).toBeFocused()
  await page.keyboard.press('Escape'); await expect(row).toBeFocused()
})
test('app removal survives refresh and reload and hidden playlists can be restored', async ({ page }) => {
  await load(page, true)
  await page.getByRole('button', { name: 'Actions for playlist List.m3u8', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Remove from app', exact: true }).click()
  await expect(page.locator('.playlist-row')).toHaveCount(0)
  await page.getByRole('button', { name: 'Refresh library', exact: true }).click()
  await expect(page.locator('.playlist-row')).toHaveCount(0)
  await page.waitForTimeout(400); await page.reload()
  await expect(page.getByText('Reconnect your music', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Manage playlists', exact: true }).click()
  await page.getByRole('button', { name: 'Restore', exact: true }).click()
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await expect(page.locator('.playlist-row')).toHaveCount(1)
})
for (const width of [1280, 390]) {
test(`the first-use guide can be skipped, remembered, replayed and completed at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Skip', exact: true }).click()
  await page.reload(); await expect(page.getByRole('region', { name: 'Getting started', exact: true })).toHaveCount(0)
  await page.getByRole('main').getByRole('button', { name: 'Browser capabilities', exact: true }).click()
  await page.getByRole('button', { name: 'Start tour', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Getting started guide' })).toContainText('Choose your music')
  await page.getByLabel('Select library files', { exact: true }).setInputFiles({ name: 'A.wav', mimeType: 'audio/wav', buffer: Buffer.from(wavSample()) })
  await expect(page.getByRole('region', { name: 'Getting started guide' })).toContainText('Try playing a track')
  await page.getByRole('button', { name: 'Next tip', exact: true }).click()
  await page.getByRole('button', { name: 'New playlist', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Create a playlist' }).getByRole('region')).toBeVisible()
  await page.getByRole('button', { name: 'Create draft', exact: true }).click()
  await page.getByRole('tab', { name: 'All tracks', exact: true }).click()
  await page.getByRole('button', { name: 'Add A to playlist', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Getting started guide' })).toContainText('Make the order yours')
  await page.getByRole('tab', { name: 'Playlist', exact: true }).click()
  await page.getByRole('button', { name: 'Next tip', exact: true }).click()
  const download = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export', exact: true }).click(); await download
  await expect(page.getByRole('region', { name: 'Getting started guide' })).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem('trackindex-guide-v1'))).toBe('completed')
})
}
test('sort menu, touch actions, compact controls and reduced motion remain usable', async ({ page }) => {
  await load(page, true)
  await page.getByRole('button', { name: 'Sort tracks', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Title', exact: true }).click()
  await page.getByRole('button', { name: 'Actions for A', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: /Move up/ })).toHaveAttribute('aria-disabled', 'true')
  await page.keyboard.press('Escape')
  for (const width of [320, 390, 768, 1024, 1440]) {
    await page.setViewportSize({ width, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
    await page.getByRole('button', { name: 'Actions for A', exact: true }).click()
    const menu = page.getByRole('menu', { name: 'Track actions' }); await expect(menu).toBeVisible()
    const bounds = await menu.boundingBox(); expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await page.keyboard.press('Escape')
    if (width < 768) expect((await page.getByRole('button', { name: 'Actions for A', exact: true }).boundingBox())!.width).toBeGreaterThanOrEqual(44)
  }
  await page.emulateMedia({ reducedMotion: 'reduce' })
  expect(await page.locator('.app').evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
  await page.mouse.move(0, 0)
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).focus()
  await expect(page.getByRole('tooltip')).toContainText('Collapse sidebar')
  await page.screenshot({ path: 'test-results/polished-desktop.png' })
})
